pipeline:
  build:
    image: docker.seafile.top/drone/seafile-pro-builder:python3
    pull: true
    commands:
      - export CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data
      - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
      - git clone --depth=1 --branch=master git://github.com/haiwen/seafile-test-deploy /tmp/seafile-test-deploy
      - cd /tmp/seafile-test-deploy && ./bootstrap.sh && cd -
      - ./tests/install-deps.sh
      - npm install -g requirejs
      - pip3 install -r dev-requirements.txt
      - pip3 install -r test-requirements.txt
      - .travis/test_seahub_changes.sh; rc=$?; if [[ $rc == 0 ]]; then ./tests/seahubtests.sh init && ./tests/seahubtests.sh runserver && ./tests/seahubtests.sh test; else true; fi

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
