pipeline:
  build:
    image: docker.seafile.top/drone/seafile-pro-builder:v3
    pull: true
    commands:
      - export TRAVIS=1
      - export CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data
      - cd /tmp/seafile-test-deploy && git fetch origin python3:python3 && git checkout python3
      - ./bootstrap.sh && cd -
      - cd /drone/src/github.com/haiwen/seahub
      - ./tests/install-deps.sh
      - .travis/test_seahub_changes.sh; rc=$?; if test "$rc" -eq 0; then ./tests/seahubtests.sh init && ./tests/seahubtests.sh runserver && ./tests/seahubtests.sh test; else true; fi
      - .travis/dist_and_push.sh

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
